print("TOKO MAINAN ANAK SERBA CEBAN")
print("----------------------------")
kasir = input("MASUKKAN NAMA KASIR :")
print("----------------------------")
mainan = 10000
kodebrg = input("MASUKKAN KODE BARANG       :")
print("HARGA BARANG :",mainan)
jmlh = int(input("MASUKKAN JUMLAH BELI :"))
jmlhbrg = mainan*jmlh
print("----------------------------\n")
print("STRUK BELANJA")
print("TOKO MAINAN ANAK SERBA CEBAN")
print("************************")
print("KASIR :",kasir)
print("************************")
print("Kode Barang      :",kodebrg)
print("HARGA BARANG Rp  :",mainan)
print("JUMLAH BELI      :",jmlh)
print("TOTAL BAYAR      :",jmlhbrg)
print("************************")
print("TERIMAKASIH :)\n")
