print("****DATA NILAI MAHASISWA UNIVERSITAS BSI****")
print("MATA KULIAH  :   DASAR PEMROGRAMAN\n")
print("---------------------------------------------\n")
nim = int(input("MASUKKAN NIM  : "))
nama = str(input("MASUKKAN NAMA LENGKAP   : "))
nilai = float(input("MASUKKAN NILAI TUGAS   : "))
absen = float(input("MASUKKAN NILAI ABSEN   : "))
total = (nilai+absen)/2
print("\n---------------------------------------------\n")
print("NIM SAYA ADALAH  :",format(nim))
print("NAMA SAYA ADALAH :",format(nama))
print("NILAI TUGAS  :",format(nilai))
print("NILAI ABSEN  :",format(absen))
print("---------------------------------------------")
print("TOTAL NILAI YANG SAYA PEROLEH",format(total))